#ifndef ISR80H_H
#define ISR80H_H

#include "./io.h"
#include "./heap.h"
#include "./process.h"
#include "../idt/idt.h"
#include "./shrdmem.h"
#include "./lock.h"


enum systemcommands
{
    SYSTEM_COMMAND1_PRINT,
    SYSTEM_COMMAND2_GETKEY,
    SYSTEM_COMMAND3_PUTCHAR,
    SYSTEM_COMMAND4_MALLOC,
    SYSTEM_COMMAND5_FREE,
    SYSTEM_COMMAND6_PROCESS_LOAD_START,
    SYSTEM_COMMAND7_INVOKE_SYSTEM_COMMAND,
    SYSTEM_COMMAND8_GET_PROGRAM_ARGUMENTS,
    SYSTEM_COMMAND9_EXIT,
    SYSTEM_COMMAND10_SHMGET,
    SYSTEM_COMMAND11_SHMAT,
    SYSTEM_COMMAND12_SHMDT,
    SYSTEM_COMMAND13_SHMDESTROY,
    SYSTEM_COMMAND14_ACQUIRE_LOCK,
    SYSTEM_COMMAND15_RELEASE_LOCK

};

void isr80h_register_commands();


#endif
