#ifndef CONFIG_H
#define CONFIG_H

#define GDT_TOTAL_ENTRIES 6

#define KERNEL_CODE_SEGMENT_SELECTOR 0x08
#define KERNEL_DATA_SEGMENT_SELECTOR 0x10
#define USER_CODE_SEGMENT_SELECTOR 0x1b
#define USER_DATA_SEGMENT_SELECTOR 0x23

#define HEAP_SIZE 104857600
#define HEAP_BLOCK_SIZE 4096
#define HEAP_TABLE_ADDRESS 0x00007e00
#define HEAP_ADDRESS 0x01000000

#define TOTAL_NO_INTERRUPTS 512
#define NUMBER_OF_ISR80H_COMMANDS 512

#define NUMBER_OF_FILESYTEMS 12
#define NUMBER_OF_FILE_DESCRIPTORS 512
#define SECTOR_SIZE 512 // In bytes

#define PATH_NAME_LIMIT 20
#define PATH_LIMIT 20

#define NUMBER_OF_PROCESS_ALLOCATION 1024
#define NUMBER_OF_TOTAL_PROCESSES 12
#define USER_PROGRAM_STACK_SIZE 1024 * 16

#define PROGRAM_VIRTUAL_ADDRESS 0x400000
#define PROGRAM_STACK_VIRT_ADDRESS 0x3ff000
#define PROGRAM_VIRTUAL_STACK_ADDRESS_END PROGRAM_STACK_VIRT_ADDRESS - USER_PROGRAM_STACK_SIZE

#define KEYBOARD_BUFFER_SIZE 1024

#define IPC_SHRDMEM_PROCESS_COUNT 5
#define IPC_SHRDMEM_MEMORY_REGION_COUNT 5
#define IPC_SHRDMEM_MAX_SIZE 4096

#define LOCK_PROCESS_COUNT 5


#endif